"""Configuration module: Data transformation configs per source"""

# Data transformation configurations per raw data source
import pandas as pd
from datetime import datetime

# Generate extraction date for file naming
extraction_date = datetime.now().strftime("%Y%m%d") 


DATA_CONFIGS = {
    'airlines': {
        'raw_data_file': f"data/raw/airlines_{extraction_date}.json",
        'endpoint': "/airlines",
        'limit': 300000,
        'exclude_cols': [
            'id',  # Exclude 'id' from hash calculation to fix upsert issue (id is a surrogate key that changes per extraction, so it breaks duplicate detection if included in hash)
        ],       
        'fill_map': {
            'id': '',
            'fleet_average_age': 0,
            'airline_id': '',
            'callsign': '',
            'hub_code': '',
            'iata_code': '',
            'icao_code': '',
            'country_iso2': '',
            'date_founded': '',
            'iata_prefix_accounting': '',
            'airline_name': '',
            'country_name': '',
            'fleet_size': 0,
            'status': '',
            'type': '',
        },
        'dtype_map': {
            'id': 'string',
            'fleet_average_age': 'float',
            'airline_id': 'string',
            'callsign': 'string',
            'hub_code': 'string',
            'iata_code': 'string',
            'icao_code': 'string',
            'country_iso2': 'string',
            'date_founded': 'int',
            'iata_prefix_accounting': 'string',
            'airline_name': 'string',
            'country_name': 'string',
            'fleet_size': 'int',
            'status': 'string',
            'type': 'string',
        },
        'table_name': 'airlines',
        'db_path': 'data/staging/airtraffic.sqlite',
    },
    'aircraft_types': {
        'raw_data_file': f"data/raw/aircraft_types_{extraction_date}.json",
        'endpoint': "/aircraft_types",
        'limit': 5000,
        'fill_map': {
            "id": '',
            "iata_code": '',
            "aircraft_name": '',
            "plane_type_id": '',
        },
        'dtype_map': {
            'id': 'string',
            'iata_code': 'string',
            'aircraft_name': 'string',
            'plane_type_id': 'string',
        },
        'table_name': 'aircraft_types',
        'db_path': 'data/staging/airtraffic.sqlite',
    },    
    'airports': {
        'raw_data_file': f"data/raw/airports_{extraction_date}.json",
        'endpoint': "/airports",
        'limit': 200000,
        'exclude_cols': [
            'id',  # Exclude 'id' from hash calculation to fix upsert issue (id is a surrogate key that changes per extraction, so it breaks duplicate detection if included in hash)
        ],               
        'fill_map': {
            "id": '',
            "airport_name": '',
            "iata_code": '',
            "icao_code": '',
            "latitude": 0,
            "longitude": 0,
            "geoname_id": '',
            "timezone": '',
            "gmt": '',
            "phone_number": '',
            "country_name": '',
            "country_iso2": '',
            "city_iata_code": '',
        },
        'dtype_map': {
            "id": "string",
            "airport_name": "string",
            "iata_code": "string",
            "icao_code": "string",
            "latitude": 'float',
            "longitude": 'float',
            "geoname_id": "string",
            "timezone": "string",
            "gmt": "string",
            "phone_number": "string",
            "country_name": "string",
            "country_iso2": "string",
            "city_iata_code": "string",
        },
        'table_name': 'airports',
        'db_path': 'data/staging/airtraffic.sqlite',
    },
    'airplanes': {
        'raw_data_file': f"data/raw/airplanes_{extraction_date}.json",
        'endpoint': "/airplanes",
        'limit': 1000000,
        'exclude_cols': [
            'id',  # Exclude 'id' from hash calculation to fix upsert issue (id is a surrogate key that changes per extraction, so it breaks duplicate detection if included in hash)
        ],       
        'fill_map': {
            "id": '',
            "iata_type": '',
            "airplane_id": '',
            "airline_iata_code": '',
            "iata_code_long": '',
            "iata_code_short": '',
            "airline_icao_code": '',
            "construction_number": '',
            "delivery_date": pd.NaT,
            "engines_count": 0,
            "engines_type": '',
            "first_flight_date": pd.NaT,
            "icao_code_hex": '',
            "line_number": '',
            "model_code": '',
            "registration_number": '',
            "test_registration_number": '',
            "plane_age": 0,
            "plane_class": '',
            "model_name": '',
            "plane_owner": '',
            "plane_series": '',
            "plane_status": '',
            "production_line": '',
            "registration_date": pd.NaT,
            "rollout_date": pd.NaT,
        },
        'dtype_map': {
            "id": 'string',
            "iata_type": 'string',
            "airplane_id": 'string',
            "airline_iata_code": 'string',
            "iata_code_long": 'string',
            "iata_code_short": 'string',
            "airline_icao_code": 'string',
            "construction_number": 'string',
            "delivery_date": 'datetime',
            "engines_count": 'int',
            "engines_type": 'string',
            "first_flight_date": 'datetime',
            "icao_code_hex": 'string',
            "line_number": 'string',
            "model_code": 'string',
            "registration_number": 'string',
            "test_registration_number": 'string',
            "plane_age": 'int',
            "plane_class": 'string',
            "model_name": 'string',
            "plane_owner": 'string',
            "plane_series": 'string',
            "plane_status": 'string',
            "production_line": 'string',
            "registration_date": 'datetime',
            "rollout_date": 'datetime',
        },
        'table_name': 'airplanes',
        'db_path': 'data/staging/airtraffic.sqlite',
    },    
    'flights': {
        'raw_data_file': "data/raw/flights_data.json",
        'endpoint': "/flights",
        'limit': 1000000,
        'exclude_cols': [
            'departure_airport',
            'departure_timezone',
            'arrival_airport',
            'arrival_timezone',
            'airline_name',
            'flight_codeshared_airline_name',
        ],
        'fill_map': {
            "flight_date": pd.NaT,
            "flight_status": '',
            "departure_iata": '',
            "departure_icao": '',
            "departure_terminal": '',
            "departure_gate": '',
            "departure_delay": 0,
            "departure_scheduled": pd.NaT,
            "departure_estimated": pd.NaT,
            "departure_actual": pd.NaT,
            "departure_estimated_runway": '',
            "departure_actual_runway": '',
            "arrival_iata": '',
            "arrival_icao": '',
            "arrival_terminal": '',
            "arrival_gate": '',
            "arrival_baggage": '',
            "arrival_scheduled": pd.NaT,
            "arrival_delay": 0,
            "arrival_estimated": pd.NaT,
            "arrival_actual": pd.NaT,
            "arrival_estimated_runway": '',
            "arrival_actual_runway": '',            
            "airline_iata": '',
            "airline_icao": '',
            "flight_number": '',
            "flight_iata": '',
            "flight_icao": '',
            "flight_codeshared_airline_iata": '',
            "flight_codeshared_airline_icao": '',
            "flight_codeshared_flight_number": '',
            "flight_codeshared_flight_iata": '',
            "flight_codeshared_flight_icao": '',
            "aircraft_registration": '',
            "aircraft_iata": '',
            "aircraft_icao": '', 
            "aircraft_icao24": '', 
            }, 
        'dtype_map': { 
            "flight_date": 'datetime', 
            "flight_status": 'string', 
            "departure_iata": 'string', 
            "departure_icao": 'string', 
            "departure_terminal": 'string', 
            "departure_gate": 'string', 
            "departure_delay": 'int', 
            "departure_scheduled": 'datetime', 
            "departure_estimated": 'datetime', 
            "departure_actual": 'datetime', 
            "departure_estimated_runway": 'string', 
            "departure_actual_runway": 'string', 
            "arrival_iata": 'string', 
            "arrival_icao": 'string', 
            "arrival_terminal": 'string', 
            "arrival_gate": 'string', 
            "arrival_baggage": 'string',
            "arrival_scheduled": 'datetime',
            "arrival_delay": 'int',
            "arrival_estimated": 'datetime',
            "arrival_actual": 'datetime',
            "arrival_estimated_runway": 'string', 
            "arrival_actual_runway": 'string',            
            "airline_iata": 'string', 
            "airline_icao": 'string', 
            "flight_number": 'string', 
            "flight_iata": 'string', 
            "flight_icao": 'string', 
            "flight_codeshared_airline_iata": 'string', 
            "flight_codeshared_airline_icao": 'string', 
            "flight_codeshared_flight_number": 'string', 
            "flight_codeshared_flight_iata": 'string', 
            "flight_codeshared_flight_icao": 'string', 
            "aircraft_registration": 'string', 
            "aircraft_iata": 'string', 
            "aircraft_icao": 'string', 
            "aircraft_icao24": 'string', 
        },
        'table_name': 'flights',
        'db_path': 'data/staging/airtraffic.sqlite',
    },        
}
